### ISSUE TITLE
destroy() method invalid

### ISSUE THREAD

**Issue by zszq** [zakjan/pixi-graph#7] opened 2021-06-23 02:47 UTC
Hello, thank you for the case, but I have a problem. When I use the <destroy()> method to destroy and create a new instance again, the memory will continue to increase, and then it will prompt (Too many active WebGL contexts. Oldest context will be lost.), how do you guess that the instance can be truly destroyed?

**Comment by zakjan** [comment] 2021-06-27 14:51
Thanks for the report, I'll investigate it. "Too many active WebGL contexts" error is weird, because WebGL context is created by PIXI and PIXI instance is destroyed in pixi-graph destroy method.

**Comment by zakjan** [comment] 2022-01-23 16:48
Closing, can't reproduce.

**Closed by zakjan** 2022-01-23 16:48 UTC
