### ISSUE TITLE
How to display two parallel sides instead of a line?

### ISSUE THREAD

**Issue by zszq** [zakjan/pixi-graph#4] opened 2021-05-26 15:24 UTC
How to display two parallel sides instead of a line? please help me！

**Comment by zakjan** [comment] 2021-05-27 05:21
Hi, I'm sorry but curved lines are not supported yet. Duplicate of #6

**Closed by zakjan** 2021-05-27 05:21 UTC

**Comment by zszq** [comment] 2021-05-27 06:15
Is there a way to support two non-coincident parallel lines between two nodes? These two lines are target and source for each other. I am encountering this problem now, which is very tricky. Please give me a hint.

**Comment by zszq** [comment] 2021-05-27 07:10
Is there a way to support two non-coincident parallel lines between two nodes? These two lines are target and source for each other. I am encountering this problem now, which is very tricky.
When there is a large amount of data, how to monitor the completion of rendering and display it? I want to add a progress bar before this. . .
Please give me some hints.

**Comment by zakjan** [comment] 2021-05-28 12:40
As much as I would like to be able to help you, this library is not ready yet to support curved or parallel edges, and my priorities are elsewhere currently. If you depend on it in a production application, would you mind if I ask you to [get in touch directly](https://zakjan.cz/) to discuss a possibility of sponsored development? Otherwise I would recommend to switch to another library. Thanks for your comprehension.
